### ISSUE TITLE
Request new features - Local markdown file

### ISSUE THREAD

**Issue by woosungchoi** [draftbox-co/gatsby-ghost-novela-theme#2]
Wow, that's really cool! Can't I create a post with a local markdown file? It would be more popular if it were possible.

**Comment by thandaanda** [comment]
Hi @woosungchoi ,

Since this theme uses Ghost as a source, we have not provided support for using local markdown file.

You can use [Novela by Narative](https://github.com/narative/gatsby-theme-novela/) theme which provides support for local markdown file.

**Comment by woosungchoi** [comment]
Thank you!
